id: 4dbd4eb6bcdf42b78f95fa656398222d
initial_creation_type: ocr
source_metadata:
  volumes:
    09f611eb9e5344b982b773d89b5b759f:
      base_file: v064.txt
      image_group_id: I1PD95910
      title: བླ་མའི་བྱ་བའི་རིམ་པ།
      total_pages: 1498
      volume_number: 65
